### ISSUE TITLE
Logging Capability

### ISSUE THREAD

**Issue by felixguerrero12** [WangYihang/Platypus#10]
#### Description
```
Adding logging capability to command sent, received, and both.
```

#### Reproduce
1. `go run platypus.go`
2. `Run 0.0.0.0 8080`
...

#### Expected behavior
Log commands and its output sent to the client for each specific session folder using hashes/codenames. Add "old_session_list" command to provide the possibility to view previous sessions. Use severity levels to manage your Golang logs volume by separating them into three categories - command sent, output received, and the combination of both.

- "print_history + md5hash/codename"
- https://github.com/gologme/log

#### Current behavior
No logging.

#### Environments
 - Standard

**Comment by WangYihang** [comment]
@felixguerrero12 Could you please to elaborate the `the combination of both`.

the data that hacker sent to the puppet will be rendered in one color, the reply of the puppet will be rendered in a different color.
I am confused about the `the combination of both`

Am I right...?

**Comment by felixguerrero12** [comment]
I was hoping for the possibility of adding three different logging capability:
1. What commands was sent by the operator with a timestamp.
2. The output of the command by the operator with a timestamp.
3. The combination of both the STDIN and STDOUT.

in_ md5hash.log, out_ md5hash.log, combine_ md5hash.log
