### ISSUE TITLE
Ubuntu 20.04编译错误

### ISSUE THREAD

**Issue by xiaosage666** [WangYihang/Platypus#107]
参照师傅的文档 如下编译：
准备一个纯净的 Ubuntu 20.04 环境，然后执行如下命令：
sudo apt update
sudo apt install -y curl make
git clone https://github.com/WangYihang/Platypus.git
cd Platypus
make install_dependency
make release
编译成功后，发行版将会位于 ./build 文件夹中

编译最后一步的时候总是报错  测试的环境均为Ubuntu20.04 并且在kali等Linux报错基本如图所示  网络均正常 均能访问外网等服务
![11](https://user-images.githubusercontent.com/77220702/152421206-a45e0b65-a62e-4304-8abc-aca9f7ceea1d.png)

还有个bug 在web打开终端  输入了命令 不小心把这个终端退出了 然后web界面就报错500了 不能正常显示和所有的功能了，必须要杀死进程 重新运行二进制文件 才恢复正常 但是这样实际测试的话 连续二次杀死进程 重新运行鸭嘴兽 大概率目标不会重连我的vps 也就是shell 中断了  ，并且我搭建在vps上面 为啥web后台地址 只能在我vps上面的浏览器访问127.0.0.1:7331 ，理论上不应该我能访问的vps公网ip上面的7331端口吗 这样我就能把shell分享给其他小伙伴了 ，目前犹豫编译出问题  ，暂时没办法在编译最新的code，也不知道问题出现在哪里，以上问题用的来自于最新的 Release 版 V1.5.0,希望师傅能解答一下我的问题 ，谢谢了 ，祝福师傅新年快乐。

![22](https://user-images.githubusercontent.com/77220702/152423152-1019120d-41ab-46bd-8019-092834a104f4.png)
![33](https://user-images.githubusercontent.com/77220702/152423499-b2c1c83c-f7da-40e3-9c55-78f549b45a34.png)
![44](https://user-images.githubusercontent.com/77220702/152423509-0104d70d-27d3-4df1-bf85-be79d30d3312.png)
![55](https://user-images.githubusercontent.com/77220702/152423515-68f7681e-14a0-4b5e-9a26-5a789a8dcd45.png)
![66](https://user-images.githubusercontent.com/77220702/152423723-3ce0adb2-e4f2-4d13-a51f-238842e32c6e.png)

**Comment by WangYihang** [comment]
感谢师傅反馈，这两个问题之前已经有师傅遇到了，并且已经被解决。

**Comment by WangYihang** [comment]
> 我搭建在vps上面 为啥web后台地址 只能在我vps上面的浏览器访问127.0.0.1:7331 ，理论上不应该我能访问的vps公网ip上面的7331端口吗 这样我就能把shell分享给其他小伙伴了 

解决方案：
1. 先运行一次 Platypus，让它生成 config.yml
2. 修改 [`config.yml`](https://github.com/WangYihang/Platypus/blob/master/assets/config.example.yml#L26-L27) 的 `restful.host` 属性为 `0.0.0.0`。
3. 再次运行 Platypus

**Comment by WangYihang** [comment]
> 编译最后一步的时候总是报错

已解决。麻烦师傅重新 clone 并重新编译一次即可，我看看这边能不能发一个 hotfix。

我这边的测试环境是 Ubuntu 20.04 x64 Vultr Los Angeles。

**Comment by WangYihang** [comment]
Pre-Release 已发。

* https://github.com/WangYihang/Platypus/releases/tag/v1.5.1
