### ISSUE TITLE
Color coding output

### ISSUE THREAD

**Issue by felixguerrero12** [WangYihang/Platypus#11]
#### Description
```
Color coding the received stdout to separate the two operations.
```

#### Reproduce
1. `go run platypus.go`
2. `Run 0.0.0.0 8080`
...

#### Current behavior
Both STDIN and STDOUT have the same color which can be confusing when interaction within a operation.

#### Environments
 - Standard.

**Comment by WangYihang** [comment]
The task is done. @felixguerrero12 
Examples:
![image](https://user-images.githubusercontent.com/16917636/75606477-325d0d80-5b28-11ea-93ad-11593b8525fd.png)
![image](https://user-images.githubusercontent.com/16917636/75606489-4c96eb80-5b28-11ea-857d-faf62d8fd127.png)

If there is any problem, please feel free to open an issue~ thank you for your suggestion, bro.
