### ISSUE TITLE
添加 Linux arm64 的打包版本

### ISSUE THREAD

**Issue by No-Github** [WangYihang/Platypus#120]
希望可以添加 Linux arm64 的打包版本，麻烦师傅了😀

**Comment by WangYihang** [comment]
@No-Github 好的，感谢建议。

**Comment by WangYihang** [comment]
欸，问一下师傅你的需求是要在 arm64 上运行控制端（Platypus）还是要通过 Termite 来控制 arm64 的机器呢？

如果是后者的话，暂时还不能做到。（后续，我会把 Platypus 和 Termite 分成两个项目来维护。这样就可以让用户选择给 Victim 发送哪个架构的 Termite 二进制程序了。但是目前只能发送 amd64 Linux 的 Termite，也就是说，目前只能通过 Termite 控制 Linux amd64 的机器）

如果是前者，我稍后会把 arm64 的 Platypus 添加到 [v1.5.1](https://github.com/WangYihang/Platypus/releases/tag/v1.5.1) 里。

**Comment by WangYihang** [comment]
已解决 [1]。

[1] https://github.com/WangYihang/Platypus/releases/download/v1.5.1/platypus_linux_arm64

**Comment by No-Github** [comment]
是在 arm64 上运行控制端

**Comment by No-Github** [comment]
谢谢师傅🙏
