### ISSUE TITLE
软件好像没法后台运行

### ISSUE THREAD

**Issue by qq1601201705** [WangYihang/Platypus#122]
环境: Ubuntu 20.04LTS云服务器
命令: nohup ./plaxxx &
感觉这个软件应该放在服务器比较合适吧？后台运行应该挺需要的。
另外这个软件很赞！期待后续加入一些渗透测试工具

**Comment by qq1601201705** [comment]
查看nohup.out

syscall.SIGTERM, Exit? [Y/N]

**Comment by WangYihang** [comment]
> 环境: Ubuntu 20.04LTS云服务器 命令: nohup ./plaxxx & 感觉这个软件应该放在服务器比较合适吧？后台运行应该挺需要的。 另外这个软件很赞！期待后续加入一些渗透测试工具

感谢反馈，已加入 TODO list。

给师傅提供一个临时解决方案：

```bash
sudo apt install tmux
tmux new -s platypus ./platypus
```

**Comment by WangYihang** [comment]
后续会出一个前后端分离的版本。服务端只负责接收 Shell，客户端可以跑在自己机器上连接服务端，从而管理服务端的 Shell。

**Comment by qq1601201705** [comment]
另外我在Ubuntu上使用screen也成功后台了

apt install screen
screen ./plaxxxxx

> 后续会出一个前后端分离的版本。服务端只负责接收 Shell，客户端可以跑在自己机器上连接服务端，从而管理服务端的 Shell。
这个想法感觉很棒！当然我觉得在服务器上开放一个带验证的网页端还是需要的，毕竟有时候更方便的是服务端和客户端都在服务器上，通过web页面访问
回复很快哈哈哈哈哈，牛

**Comment by WangYihang** [comment]
> 当然我觉得在服务器上开放一个带验证的网页端还是需要的，毕竟有时候更方便的是服务端和客户端都在服务器上，通过web页面访问

好主意！我后面有空了整一下子。 @_<

**Comment by qq1601201705** [comment]
> > 当然我觉得在服务器上开放一个带验证的网页端还是需要的，毕竟有时候更方便的是服务端和客户端都在服务器上，通过web页面访问
> 
> 好主意！我后面有空了整一下子。 @_<

我现在是后台运行platypus然后临时端口转发到开放端口，访问发现web端只有连接shell和upgrade功能，建议其他指令应该也要支持才行0.0

**Comment by WangYihang** [comment]
对，确实。
目前暂时还没有时间把所有命令行的功能全迁移到 Web 上。
