### ISSUE TITLE
[Feature Requests] Encryption support.

### ISSUE THREAD

**Issue by ghost** [WangYihang/Platypus#15]
#### Description
```
I would like for the platypus listener to support encryption such as AES or SSL.
Describe your problem here
```
The Platypus server currently does not support encryption which means the commands are send in cleartext over the network.
#### Reproduce
1. `go run platypus.go`
2. `Run 0.0.0.0 8080`
...
3. `Encrypt [hash of listener] /path/to/ssl.crt /path/to/ssl.key`
#### Expected behavior
The entire connection has end to end encryption
#### Current behavior
The connection can be eavesdropped by anyone using a wire sniffer.
#### Environments
 - OS: Ubuntu 18.04.1 LTS
 - Version: 1.1.0

**Comment by WangYihang** [comment]
Got it, nice idea, I will add this idea into TODO list. thank you so much!
