### ISSUE TITLE
你好，编译报错了。

### ISSUE THREAD

**Issue by lrtoper** [WangYihang/Platypus#150]
#### Description
编译报错

#### Reproduce
make all

#### Expected behavior

env GOOS=linux GOARCH=amd64 go build -ldflags="-s -w " -trimpath -o ./build/termite/termite_linux_amd64 cmd/termite/main.go
go: github.com/dchest/captcha@v1.0.0: missing go.sum entry; to add it:
        go mod download github.com/dchest/captcha
go: github.com/dchest/captcha@v1.0.0: missing go.sum entry; to add it:
        go mod download github.com/dchest/captcha
make: *** [Makefile:33: build_termite] Error 1

#### Environments
 - OS: Ubuntu 20.04
 - Version: 1.5.0
 - go version go1.18.2 linux/amd64

**Comment by WangYihang** [comment]
![image](https://user-images.githubusercontent.com/16917636/196573970-f0edc0ec-e097-4f66-82a5-25059c8f60ee.png)

**Comment by lrtoper** [comment]
感谢
