### ISSUE TITLE
Possible Feature: Command Line Arguments

### ISSUE THREAD

**Issue by k1epto** [WangYihang/Platypus#19]
Is there any way you can add the ability to launch the 'Run IP PORT' command from the command line when you launch platypus?  like platypus -Run IP PORT or something?? that way I can have it setup and ready with a simple command, instead of running the application, then giving it commands to listen or whatever...... I hope that makes sense.

**Comment by WangYihang** [comment]
Cool idea. I will add it to the todo list, thank you for your reporting!@bipolarmorgan

**Comment by WangYihang** [comment]
#16 Maybe helpful.
By the way, I am working on adding command-line arguments.
