### ISSUE TITLE
Case insensitive CLI

### ISSUE THREAD

**Issue by l50** [WangYihang/Platypus#23]
Could you make the CLI case insensitive? It would be nice to have the option to input `help` or `Help` and have the tool function as expected.

**Comment by WangYihang** [comment]
The task is done, @l50. Feel free to give it a try, [v1.2.1](https://github.com/WangYihang/Platypus/releases/tag/v1.2.1)
If the implementation have any bug, please let me know~ thank you so much~
![image](https://user-images.githubusercontent.com/16917636/75604710-94147c00-5b16-11ea-8ee2-274b8a5a99a3.png)
![image](https://user-images.githubusercontent.com/16917636/75605137-09824b80-5b1b-11ea-9313-ed1d42dcbc1d.png)
![image](https://user-images.githubusercontent.com/16917636/75605142-11da8680-5b1b-11ea-93f5-b5eb7d6be31f.png)

**Comment by l50** [comment]
Initial tests LGTM, thanks!

**Comment by l50** [comment]
Also, I forgot to mention previously that I ended up using your tool in a demo for a DEF CON talk I gave last year: https://youtu.be/cA0LGfxQS2g?t=2093

Great work, keep it up!

**Comment by WangYihang** [comment]
> Also, I forgot to mention previously that I ended up using your tool in a demo for a DEF CON talk I gave last year: https://youtu.be/cA0LGfxQS2g?t=2093
> 
> Great work, keep it up!

Cool! I really appreciate it that you are using this tool, feel free to leave some advice for this repo. Thanks a lot!
