### ISSUE TITLE
Feature Request: Set all nodes to interact

### ISSUE THREAD

**Issue by rootabeta** [WangYihang/Platypus#31]
It would be useful to be able to set all clients to interact mode for datadispatcher, or deselect them, rather than having to specify them individually.

**Comment by WangYihang** [comment]
Thank you bro for your advice. 
Actually, there is a method to execute one command to multiple sessions. That is the `Switching` meta-command.

When you use the `List` meta-command, you will see the `GROUP` column which indicates that whether the session is selected or not, namely active or inactive. We can use the `DataDispatcher` meta-command to send one command to all sessions whose `GROUP` is true at the same time. Using the `Switching` meta-command can flip the `GROUP` property.

eg:
1. There are 3 available sessions with the `GROUP` property set to `false`.
![image](https://user-images.githubusercontent.com/16917636/109441422-33dd5080-7a70-11eb-8f9e-bdb4104c2a54.png)
2. We can use the `Switching`  meta-command to interact with session `639ce2` and session `4baedf`.
```
Switching 639ce2
Switching 4baedf
```
3. Then we can re-list all sessions
![image](https://user-images.githubusercontent.com/16917636/109441741-10ff6c00-7a71-11eb-9c2b-00a08e298fe5.png)

4. Finally, we can use the `DataDispatcher` meta-command to send a single command to all switched sessions. (the command output will not be displayed unless you interact with the single command.)

BUT, This feature is not well-implemented, I still can not figure out how to provide a user-friendly user interface in the command line. Maybe a web frontend application will be a better choice (Platypus just acts as a backend service). In addition, Platypus has the RESTful API, so everyone who is interested in this project can write some frontend code to manipulate Platypus, including fetching all sessions, executing a command on one session, and so on.

**Comment by WangYihang** [comment]
Ah 😭 , sorry, I think I misunderstood your thought... 
I got it. I will work on it.

**Comment by WangYihang** [comment]
@rootabeta Now, the default Switch status is set to `true`, namely, all new sessions will be added to the dispatcher group. In the same time, the `Switching` meta-command is available to change the `GROUP` property for all sessions of a server by providing the hash of the server.
eg: 
![image](https://user-images.githubusercontent.com/16917636/109471487-c94a0600-7aab-11eb-82b6-789b2b98effa.png)

```
Switching 999e5d # notice the hash `999e5d` is the hash of the server, not the client.
```
then all the `GROUP` property of clients (namely, `639ce2` and `61ef17`) under the server (`999e5d`) will be set to `true`.
