### ISSUE TITLE
来自同一出口IP的会话如何进行管理？

### ISSUE THREAD

**Issue by weinull** [WangYihang/Platypus#33]
* 多个GameBox通过同一出口IP访问Platypus，Platypus只会保留一个会话，因为多个GameBox的连接属于相同IP会自动断开新建的会话。
* 每次反弹shell都会使用随机端口，所以使用IP+端口进行唯一性判断也是不行的。

**问题：**
有没有其他好的办法可以解决这种同一出口IP的多会话管理？

**Comment by WangYihang** [comment]
1. 目前 Platypus 可以通过 `BlockSameIP` 命令关闭，关闭后，对于所有 income 的 GameBox，都不会自动断开。
2. 或许可以通过例如 MAC 地址、用户名等一系列属性来唯一标识（会加入 TODO List）。
感谢反馈，师傅有什么想法也可以随便提~

**Comment by WangYihang** [comment]
之后会把 `BlockSameIP` 等功能集成到配置文件里。

**Comment by weinull** [comment]
> 1. 目前Platypus可以通过`BlockSameIP`命令关闭，关闭后，对于所有收入的GameBox，都不会自动替换。
> 2. 或许可以通过例如MAC地址，用户名等类别属性来唯一标识（会加入TODO List）。
>    感谢反馈，师傅有什么想法也可以随便提〜

我觉得 **IP+MAC地址+用户名** 来做唯一标识的方式可行（MAC地址可以当shell连过来时自动执行命令来进行获取，或者不用MAC地址使用其他唯一的硬件ID之类的）
这样的话可以解决同一出口IP多会话的问题，还可以区分不同用户的权限，比如同一主机普通用户反弹的shell跟root用户反弹的shell

**Comment by WangYihang** [comment]
> 这样的话可以解决同一出口IP多会话的问题，还可以区分不同用户的权限，比如同一主机普通用户反弹的shell跟root用户反弹的shell

区分不同用户的权限已经可以做到了，使用 `List` 就可以，如下图：
![image](https://user-images.githubusercontent.com/16917636/111602731-9d01e980-880e-11eb-8684-ce43fada5251.png)

**Comment by WangYihang** [comment]
已解决，目前通过客户端哈希来判断新连接的客户端是否已经被攻陷（仅支持 Linux 系统）。使用 IP、用户名、操作系统以及网卡 MAC 地址来计算哈希，这样基本上可以保证同一个用户反弹的 Shell 只有一个。并且可以区分同一台机器不同用户反弹的 Shell。
当新连接接入的时候，通过哈希表查询，若存在，则断开新连接；若不存在，则添加新连接。

另外，取消 `BlockSameIP` 功能。

**Comment by weinull** [comment]
解决速度非常快！👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻
