### ISSUE TITLE
WebUI Unable to connect to firewalled client's

### ISSUE THREAD

**Issue by adebroise** [WangYihang/Platypus#57]
WebUI uses web socket to connect to client machines, however if behind a firewall you receive the following on a loop:

Reconnecting
Connection Closed

Command line version allows interactive shell as normal. Would like to be able to connect via the WebUI to the client using the same approach (ie. no port forwarding needed).

**Comment by WangYihang** [comment]
It seems a good idea, maybe we need more sophisticated tunneling methods (eg: UDP, TCP-over-DNS, TCP-over-ICMP).
I will add this to the TODO list. Thanks!
