### ISSUE TITLE
Makefile don't install nvm correctly

### ISSUE THREAD

**Issue by KuroChu** [WangYihang/Platypus#64]
#### Description
When I try to run the [Makefile](https://github.com/WangYihang/Platypus/blob/d13e22fc8490affa56a6bbb846546a4aee33c3e4/Makefile) it seems like it installs nvm (line 9) but at 'sudo nvm install --lts'(line 10) it gives me an error that nvm does not exist.

#### Reproduce
1. `cd Platypus`
2. `make`
...

#### Expected behavior
Should run and install without an error i think

#### Current behavior
Doesn't install nvm correctly

#### Environments
 - OS: Ubuntu 20.04.2 LTS
-  OS: Ubuntu server 20.04.2
-  OS: Kali 2021.1
-  OS: Parrot 4.11.2
-  OS: Debian 10
 - Version: 1.5.0

#### Extra
In Line 5 'add-apt-repository...' takes forever but this is due to an ipv6 DNS routing issue which i found out can be solved by deactivating ipv6 until reboot and everything is fine

**Comment by WangYihang** [comment]
Thanks for reporting, I am working on it.

**Comment by WangYihang** [comment]
Solved. Please check it out. @KuroChu 
```bash
git clone https://github.com/WangYihang/Platypus
cd Platypus
sudo apt install -y make curl
make install_dependency
make release
```
