### ISSUE TITLE
Crash when access `/api/server`

### ISSUE THREAD

**Issue by WangYihang** [WangYihang/Platypus#69]
#### Description
```
Describe your problem here
```

#### Reproduce

1. `go run platypus.go`
2. `curl http://1.3.3.7/api/server`

#### Expected behavior

return servers information

#### Current behavior

platypus got crash.

#### Screenshots/Terminal log

```
2021/08/16 15:50:09 [Recovery] 2021/08/16 - 15:50:09 panic recovered:
json: unsupported type: func() (io.ReadCloser, error)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/render/json.go:59 (0xa546a6)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:841 (0xa5acc8)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:884 (0xaf9b04)
/home/runner/work/Platypus/Platypus/lib/context/restful.go:334 (0xaf99a1)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xa6ab90)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 (0xa6ab77)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xa69c13)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 (0xa69bd2)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xa60d4f)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 (0xa60d36)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 (0xa607ec)
/opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:2887 (0x798082)
/opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:1952 (0x7934ac)
/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/asm_amd64.s:1371 (0x46e900)

```

![DNN6@Y13B$HHQ6Z%BCPU9YF](https://user-images.githubusercontent.com/16917636/129545570-0c455bfb-d97a-4405-abf1-948ff199aa1c.png)

#### Environments
 - OS: Ubuntu 20.04.1 LTS
 - Version: 1.5.0

**Comment by WangYihang** [comment]
Reported by @rama291041610

**Comment by xinhuang** [comment]
The same issue happens to me. It occurs after the upgraded shell connects back for a while, usually 5~10 minutes. The shell is still alive though.

**Comment by WangYihang** [comment]
Thanks for reporting, I am working on it. @xinhuang

**Comment by WangYihang** [comment]
Fixed (I guess 🤣 ). 

### How does this bug appears

The root cause is that I misused the struct tags for the package [encoding/json](https://pkg.go.dev/encoding/json). 

This problem can be solved by adding `json:"-"` after the unexported field of `TermiteClient`, see [here](https://github.com/WangYihang/Platypus/blob/2e5b74b9a06cdc530a3deb0cd751011a4d03c524/internal/context/termite.go#L59-L66).

> https://pkg.go.dev/encoding/json
> ```
> // Field is ignored by this package.
> Field int `json:"-"`
> ```

## Pickup this fix

### Setup Compilation Environment

* A new fresh Vultr Ubuntu instance (Memory at least 2GB)

```
root@vultr:~/Platypus# uname -a
Linux vultr.guest 5.11.0-17-generic #18-Ubuntu SMP Thu May 6 20:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
root@vultr:~/Platypus# cat /etc/issue
Ubuntu 21.04 \n \l
```

### Build

```bash
sudo apt install -y make
git clone https://github.com/WangYihang/Platypus
cd Platypus
make
cd build/platypus
./platypus_linux_amd64
```

**Comment by WangYihang** [comment]
Pre-Release 已发。

* https://github.com/WangYihang/Platypus/releases/tag/v1.5.1
